### ISSUE TITLE
How to run it?

### ISSUE THREAD

**Issue by mateuszjarzewski** [ThomasKliszowski/json_reindent#2]
Title tells the story. There is nothing about it in readme, nowhere, nothing, sad panda.
I'm serius, I can see that is uses json.dumps() great, but how in the hell to use it?

Nevermind
I just install https://github.com/dzhibas/SublimePrettyJson
and press ctrl + alt + j, like readme tell me to...

Have no time for crappy undocumented plugins like yours.

**Comment by ThomasKliszowski** [comment]
Hi,

You are my first grumpy user! You can be proud of you :).

This is just a really simple plugin which, I thought, has no need of a documentation.
Like all Sublime Text plugins, you juste have to press Ctrl+Shift+P and type something like... I don't know, Json Reindent?
I don't like to provide default key bindings like SublimePrettyJson do because of conflicts or user preferences.

Maybe I was wrong because you are here to prove that my plugin needs a documentation.
I will do that as soon as possible.

I hope that you did not spend too many time with my "crapy" plugin. Your time seems to be so important :).

**Comment by mateuszjarzewski** [comment]
I need no documentation.
I need single line of text that describes how to use it.
Without that, you are lazy noob.

**Comment by giovannibonetti** [comment]
Nevermind that guy. This plugin works great! I am a happy user.

**Comment by evoactivity** [comment]
Guy is grumpy as hell but I also had no idea how to run it. My first port of call is not ctrl + shift + p, I usually look for a menu item or a key binding to use.

**Comment by kamranayub** [comment]
:+1: Agree did not know how to use it :( But thanks for making this!

**Comment by ThomasKliszowski** [comment]
Sorry for the lack of documentation, guys.
I just added a basic **Usage** section in the README.
